### PR TITLE
asHashMap without args

### PR DESCRIPTION
**Pull request by michaelkuechler**
- class cast exception in case of traversable with elements not extending Map.Entry

### CODE REVIEW

**Comment by julien-may** [comment]
you can't be serious, right?

**Comment by michaelkuechler** [comment]
@julien-may :
> you can't be serious, right?

well… JEIN ?
when it comes to dealing with maps, query is the horror at the moment! this here would make things a lot more convenient. on the other hand I understand that this method is generally broken - except you're lucky enough to invoke it on a `Traversable<Map.Entry<?, ?>>`…

**Comment by michaelkuechler** [comment]
wild idea: we would not have this problem if, instead of the "asXY" methods on the Traversable, we'd have something like this:

```
package ch.julien.common.conversion;
public interface Converter {
	public <T> Collection<T> toCollection(Query<T> q) {…}
	// add your preferred subinterfaces of java.util.Collection …
	public <T extends Map.Entry<TKey, TElement> Map<TKey, TElement> toMap(Query<T> q) {…}
	// add your preferred subinterfaces of java.util.Map …
	public T[] asArray(Query<T> q} {…}
```

**Comment by michaelkuechler** [comment]
outdated

**Pull request closed without merging**
